name: Docker
on:
  push:
    tags:
      - 'v[0-9]+*'
  schedule:
    # monthly on day 15
    - cron: '15 15 15 * *'
  workflow_dispatch:

permissions:
  artifact-metadata: write
  attestations: write
  id-token: write
  packages: write

jobs:
  mini-ndn:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: mini-ndn
